version: '3'
services:
    db-mongo:
        image: mvertes/alpine-mongo:latest
        networks:
            - front-tier
        volumes:
            - /data/db:/data/db
    backend:
        build: .
        command: node ./app.js
        volumes:
            - .:/app
            - dependencies:/app/node_modules
        ports:
            - "8081:8080"
        links:
            - db-mongo
        environment:
            - PORT=8080
            - NODE_ENV=development
            - MONGO_HOST=db-mongo
        networks:
            - front-tier
networks:
    front-tier:
        driver: bridge
volumes:
    dependencies:
